"""
Neotic Backend Core - Main entry point for the FastAPI server.
"""
# pylint: disable=import-error
import os
import uvicorn
from fastapi import FastAPI, WebSocket
from src.middlewares.cors import setup_cors
from src.routes.chatroutes import ROUTER as chat_router
from src.routes.libraryroutes import ROUTER as library_router
from src.rag.websocket import handle_rag_websocket

APP = FastAPI(title="Neotic Backend Core")

# Initialize Middlewares
setup_cors(APP)

# Mount Routes
APP.include_router(chat_router, prefix="/api")
APP.include_router(library_router, prefix="/api/library")

# Handle RAG WebSockets (Consolidated from rag-visualizer)
@APP.websocket("/ws/rag")
async def websocket_rag(websocket: WebSocket):
    """
    WebSocket endpoint for real-time RAG visualization signals.
    """
    await handle_rag_websocket(websocket)

if __name__ == "__main__":
    # AUTO-DETECT SSL (Generated by Next.js --experimental-https)
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    CERT_FILE = os.path.join(PROJECT_ROOT, "certificates", "localhost.pem")
    KEY_FILE = os.path.join(PROJECT_ROOT, "certificates", "localhost-key.pem")
    USE_SSL = False

    if USE_SSL:
        print("✓ SSL DETECTED: Running backend on https://127.0.0.1:8001")
        uvicorn.run(
            "server:APP",
            host="127.0.0.1",
            port=8001,
            reload=True,
            ssl_certfile=CERT_FILE,
            ssl_keyfile=KEY_FILE
        )
    else:
        print("⚠ SSL NOT FOUND: Running backend on http://0.0.0.0:8001")
        print("To enable SSL, start the frontend first with 'npm run dev' to generate certs.")
        uvicorn.run("server:APP", host="0.0.0.0", port=8001, reload=True)
